CREATE TABLE Usuario (
	id SERIAL PRIMARY KEY,
	usuario VARCHAR(150) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	senha VARCHAR(50) NOT NULL,
	is_administrador BOOLEAN DEFAULT FALSE,
	cliente_id INTEGER,
	ativo BOOLEAN DEFAULT TRUE
);